Implement Development Platform Marketplace auto discover
maestrano/maestrano-dotnet pull request #13
Opened 2016-09-01 14:16 UTC by x4d3

- Add MnoHelper.AutoConfigure and MnoHelper.AutoConfigure(host, path, key, secret)
- Refactor Connec.Client to force it to be instantiated with a group Id.
- Remove unused using
- Remove redundant full qualification

2016-09-01 14:16 UTC, x4d3 commented
@alachaum @BrunoChauvet Could you please review ?

2016-11-25 06:06 UTC, alachaum requested changes
See my two comments. The migration notes can be done once it's merged into 1.0.0. The other one (section group) should be changed I believe.

Also we should rename the branch 1.0.0 to 1.0 and create a alpha branch for the current master branch.

Otherwise, it looks much much better 😄

2016-11-25 06:06 UTC, alachaum commented on src/Maestrano.Tests/app.config
> +  <devPlatform
The section name should be more specific as it is a general configuration file. e.g. maestranoDevPlatform

2016-11-25 06:06 UTC, alachaum commented on README.md
> +// var client = Maestrano.Connec.Client.New("cld-f7f5g4", "somePreset");
As we have breaking changes (preset syntax is different) we need to add migration notes.

2016-11-25 16:13 UTC, alachaum approved these changes

2016-11-25 16:13 UTC, alachaum commented
👍

2016-11-28 07:30 UTC, merged